apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: cloudflare
  namespace: velero
spec:
  backupSyncPeriod: 24h0m0s
  config:
    checksumAlgorithm: ''
    profile: default
    region: auto
    s3Url: dummyvalue # will be patched by postsync hook
  credential:
    key: cloud
    name: cloudflare-r2-secret
  default: true
  objectStorage:
    bucket: multi-cluster-backup
    prefix: velero
  provider: velero.io/aws
  validationFrequency: 24h0m0s